### ISSUE TITLE
Warning if running in terminal

### ISSUE THREAD

**Issue by huyz** [L-TChen/auto-dark-mode.vim#1]
I often run `vim` at the command line as well as in MacVim. How do I avoid this startup warning `AutoDark requires MacVim Snapshot 160 or later running in the GUI mode` when starting from the command line?

**Comment by L-TChen** [comment]
I guess you can load the plug-in conditionally based on where MacVim is running.

**Comment by huyz** [comment]
That's what I resorted to.  But shouldn't this detection be built into the plugin?  If it only applies to MacVim then why is it putting out an irrelevant warning in terminal mode?

**Comment by L-TChen** [comment]
Right, you’re quite right. I now changed this (81a3e86) as you suggested.
